version: "3"
services:
  mean-stack-app:
    image: smad
    build:
      context: .
      args:
        - APP_NAME=${APP_NAME}
        - APP_REPOSITORY=${APP_REPOSITORY}
    ports:
      - "${EXTERNAL_PORT}:3000"
    volumes:
      - smad-log:${LOG_FOLDER}
    environment:
      - NODE_ENV=${NODE_ENV}
      - TOKEN_SECRET=${TOKEN_SECRET}
      - LOG_LEVEL=${LOG_LEVEL}
      - DB_URL={DB_URL}
      - DB_NAME={DB_NAME}
      - LOG_FOLDER=${LOG_FOLDER}
